config/routes.rb
PhotoChallenge::Application.routes.draw do
  root 'daily_challenges#latest'

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}
  resources :challenges do
    member do
      put :vote, :defaults => {format: :json}
    end
  end

  resources :users
  resources :photos
  resources :daily_challenges, path: 'daily-challenges' do
    collection do
      get :latest
    end
  end
end

app/views/shared/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-camera"></span> Photo Challenges</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'daily_challenges' %>"><%= link_to 'Daily Challenge', latest_daily_challenges_path %></li>
        <li class="<%= 'active' if params[:controller] == 'challenges' %>"><%= link_to 'Challenges', challenges_path %></li>
        <li class="<%= 'active' if params[:controller] == 'photos' %>"><%= link_to 'Photos', photos_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img class="avatar" src="<%= current_user.profile_image_url %>" /> <%= current_user.display_name %>
              <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View Profile', current_user %></li>

              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="icon-signout"></i> Sign Out

                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class=""><a>|</a></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>