config/routes.rb
PhotoChallenge::Application.routes.draw do
  root 'daily_challenges#latest'

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}
  resources :challenges do
    member do
      put :vote, :defaults => {format: :json}
    end
  end

  resources :users
  resources :photos
  resources :daily_challenges, path: 'daily-challenges' do
    collection do
      get :latest
    end
  end
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_and_belongs_to_many :photos
  has_one :daily_challenge
  validates :description, :presence => true
  validates :user_id, :presence => true

  def self.hashtags
    Challenge.pluck(:id).map { |id| "pc#{id}" }
  end

  def self.find_by_hashtags(*hashtags)
    ids = hashtags.map { |hashtag| hashtag[2..-1] }
    Challenge.where(:id=>ids)
  end

  def hashtag
    "pc#{id}"
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_challenge, only: [:show, :edit, :update, :destroy, :vote]

  # GET /challenges
  # GET /challenges.json
  def index
    @voted = current_user ? current_user.get_up_voted(Challenge).pluck(:id) : []
    @challenges = Challenge.all.includes(:user)
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    @challenge.user = current_user

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  #def destroy
  #  @challenge.destroy
  #  respond_to do |format|
  #    format.html { redirect_to challenges_url }
  #    format.json { head :no_content }
  #  end
  #end

  def vote
    @challenge.liked_by current_user
    render json: {msg: @challenge.vote_registered? ? 'Vote registered' : 'Already voted'}
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_challenge
    @challenge = Challenge.includes(:user).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def challenge_params
    params.require(:challenge).permit(:description)
  end
end

app/helpers/challenge_helper.rb
module ChallengeHelper
  def challenge_editable(challenge)
    current_user and (challenge.user == current_user)
  end
end

app/views/challenges/_form.html.erb
<%= bootstrap_form_for(@challenge) do |f| %>
  <%= f.alert_message 'Please fix the errors below.' %>
  <%= f.text_field :description %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <a class="btn btn-default" onclick="window.history.back();">Cancel</a>
<% end %>

app/views/challenges/edit.html.erb
<% title "Edit Challenge ##{@challenge.id}" %>

<div class="page-header">
  <h1><%= content_for(:title) %></h1>
</div>

<%= render 'form' %>

app/views/challenges/index.html.erb
<% title 'Challenges' %>

<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Create New Challenge', new_challenge_path, :class => 'btn btn-primary', :role => 'button' %>
  </div>
  <h1><%= content_for(:title) %></h1>
</div>

<div class="challenges">
  <% @challenges.each do |challenge| %>
    <div class="challenge row margin-bottom" ng-controller="ChallengeDetailCtrl" ng-init="init(<%= challenge.id %>, <%= challenge.likes.count %>, <%= @voted.include?(challenge.id) %>)">
      <div class="counts col-xs-2 text-center">
        <div ng-switch on="voted">
          <div ng-switch-when="true">
            <a class="vote-link voted">
              <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
          </div>
          <div ng-switch-default>
            <a class="vote-link" href="" ng-click="vote()">
              <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
          </div>
        </div>
        {{votes}}
      </div>
      <div class="detail col-xs-10">
        <div class="description"><%= link_to challenge.description, challenge %></div>
        <div class="text-muted small">Submitted by <%= link_to challenge.user.display_name, challenge.user %> &bull; <%= pluralize challenge.photos.count, 'Photo' %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/challenges/new.html.erb
<% title 'Create New Challenge' %>

<div class="page-header">
  <h1><%= content_for(:title) %></h1>
</div>

<%= render 'form' %>

app/views/challenges/show.html.erb
<% title "Challenge ##{@challenge.id}" %>

<div class="jumbotron">
  <h1>Challenge #<%= @challenge.id %></h1>

  <div class="margin-bottom-large text-muted">Submitted
    by <%= @challenge.user.display_name %> &bull; <%= pluralize @challenge.photos.count, 'Photo' %></div>
  <% if @challenge.daily_challenge %>
    <p>
    <div class="badge alert-warning"><span class="glyphicon glyphicon-star"></span> Daily Challenge
      for <%= @challenge.daily_challenge.created_at.strftime('%Y %b %d') %></div>
    </p>
  <% end %>

  <p><%= @challenge.description %></p>

  <% if challenge_editable(@challenge) %>
    <%= link_to 'Edit', edit_challenge_path(@challenge), :class => 'btn btn-primary', :role => 'button' %>
  <% end %>
</div>

<% if @challenge.photos %>
  <%= render 'photos/photos', photos: @challenge.photos %>
<% else %>
  <div class="alert alert-info">
    No photos have been posted for this challenge.
  </div>
<% end %>